// Copyright (c) The Jaeger Authors.
// SPDX-License-Identifier: Apache-2.0
//
// Run 'make generate-mocks' to regenerate.

// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ArchiveCapable is an autogenerated mock type for the ArchiveCapable type
type ArchiveCapable struct {
	mock.Mock
}

// IsArchiveCapable provides a mock function with no fields
func (_m *ArchiveCapable) IsArchiveCapable() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsArchiveCapable")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewArchiveCapable creates a new instance of ArchiveCapable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArchiveCapable(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArchiveCapable {
	mock := &ArchiveCapable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
