// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"github.com/jaegertracing/jaeger/plugin/storage/grpc/shared/extra"
	mock "github.com/stretchr/testify/mock"
)

// PluginCapabilities is an autogenerated mock type for the PluginCapabilities type
type PluginCapabilities struct {
	mock.Mock
}

// Capabilities provides a mock function with given fields:
func (_m *PluginCapabilities) Capabilities() (*extra.Capabilities, error) {
	ret := _m.Called()

	var r0 *extra.Capabilities
	if rf, ok := ret.Get(0).(func() *extra.Capabilities); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*extra.Capabilities)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
