# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.12.11@sha256:8a790dd3468db22b1d4e7b18a176f378ff5ff6053b9c48dd4ea1fa71a24c5ba6
    container_name: clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=jaeger
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query=SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
