# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.8.24.21@sha256:0fa332a9a05ce4138b16d883f9c9d124c8d9d81cf4e52046878d537558626e49
    container_name: clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=jaeger
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query=SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
