# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: jaeger-opensearch-oci-retain
  labels:
    app.kubernetes.io/part-of: jaeger-demo
driver: blockvolume.csi.oraclecloud.com
deletionPolicy: Retain
parameters:
  backupType: full
