# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

services:
    jaeger:
      image: cr.jaegertracing.io/jaegertracing/jaeger:2.18.0@sha256:d2cbd047e44b50c11454820f84fd5f34c24a435e5301cf94fe026bf055db80b3
      ports:
        - '16686:16686'
        - '4318:4318'

    tracegen:
      image: cr.jaegertracing.io/jaegertracing/jaeger-tracegen:2.18.0@sha256:96e94561b4cf76e87fc114f2a94b409d762c3db0966dc2f71e5fb9a2022fe6ce
      environment:
        - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      command: ["-duration", "10s", "-workers", "3", "-pause", "250ms"]
      depends_on:
        - jaeger
