# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.3@sha256:f456578fc2a620a8a4f4c21d070fff1f6070345adb2be5e5626b65be72aea350
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false  # Disable security features
      - xpack.security.http.ssl.enabled=false  # Disable HTTPS
      - action.destructive_requires_name=false
      - xpack.monitoring.collection.enabled=false  # Disable monitoring features
    ports:
      - "9200:9200"

