# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: pyrra.dev/v1alpha1
kind: PrometheusServiceLevel
metadata:
  name: jaeger-query-success
  namespace: monitoring
  labels:
    app: jaeger
spec:
  target: "99"
  window: 28d
  indicator:
    ratio:
      errors:
        metric: http_server_request_duration_seconds_count{job="jaeger", http_route="/api/v3/traces", http_response_status_code=~"5.."}
      total:
        metric: http_server_request_duration_seconds_count{job="jaeger", http_route="/api/v3/traces"}
