# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: pyrra.dev/v1alpha1
kind: PrometheusServiceLevel
metadata:
  name: jaeger-receiver-success
  namespace: monitoring
  labels:
    app: jaeger
spec:
  target: "99"
  window: 28d
  indicator:
    ratio:
      errors:
        metric: otelcol_receiver_refused_spans_total{job="jaeger"}
      total:
        metric: otelcol_receiver_accepted_spans_total{job="jaeger"}
