# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

apiVersion: pyrra.dev/v1alpha1
kind: PrometheusServiceLevel
metadata:
  name: jaeger-exporter-success
  namespace: monitoring
  labels:
    app: jaeger
spec:
  target: "99"
  window: 28d
  indicator:
    ratio:
      errors:
        metric: otelcol_exporter_send_failed_spans_total{job="jaeger"}
      total:
        metric: otelcol_exporter_sent_spans_total{job="jaeger"}
