FROM python:3-alpine3.11

COPY ./mappings/* /mappings/
COPY esRollover.py /es-rollover/
COPY requirements.txt /es-rollover/

RUN pip install -r /es-rollover/requirements.txt

ENTRYPOINT ["python3", "/es-rollover/esRollover.py"]
