FROM python:3-alpine3.14
ARG TARGETARCH

COPY requirements-build.txt requirements-build.txt
COPY requirements.txt requirements.txt

RUN pip install -r requirements-build.txt
RUN pip install -r requirements.txt

COPY ./mappings/* /mappings/
COPY esRollover.py /es-rollover/
COPY esmapping-generator-linux-$TARGETARCH /usr/bin/esmapping-generator

ENTRYPOINT ["python3", "/es-rollover/esRollover.py"]
