service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    storage:
      traces: clickhouse_storage
      metrics: clickhouse_storage
  jaeger_storage:
    backends:
      clickhouse_storage: &clickhouse_config
        clickhouse:
          addresses:
            - clickhouse:9000
          database: jaeger
          auth:
            basic:
              username: default
              password: password
          create_schema: true
    metric_backends:
      clickhouse_storage: *clickhouse_config

receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: clickhouse_storage
