// Copyright (c) 2025 The Jaeger Authors.
// SPDX-License-Identifier: Apache-2.0

package tracestore

import (
	"time"

	"go.opentelemetry.io/collector/pdata/pcommon"
)

var traceID = pcommon.TraceID([16]byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1})

var now = time.Date(2025, 6, 14, 10, 0, 0, 0, time.UTC)

var singleSpan = []*spanRow{
	{
		id:                          "0000000000000001",
		traceID:                     traceID.String(),
		traceState:                  "state1",
		name:                        "GET /api/user",
		kind:                        "server",
		startTime:                   now,
		statusCode:                  "Ok",
		statusMessage:               "success",
		rawDuration:                 1_000_000_000,
		boolAttributeKeys:           []string{"authenticated", "cache_hit"},
		boolAttributeValues:         []bool{true, false},
		doubleAttributeKeys:         []string{"response_time", "cpu_usage"},
		doubleAttributeValues:       []float64{0.123, 45.67},
		intAttributeKeys:            []string{"user_id", "request_size"},
		intAttributeValues:          []int64{12345, 1024},
		strAttributeKeys:            []string{"http.method", "http.url"},
		strAttributeValues:          []string{"GET", "/api/user"},
		complexAttributeKeys:        []string{"@bytes@request_body"},
		complexAttributeValues:      []string{"eyJuYW1lIjoidGVzdCJ9"},
		eventNames:                  []string{"login"},
		eventTimestamps:             []time.Time{now},
		eventBoolAttributeKeys:      [][]string{{"event.authenticated", "event.cached"}},
		eventBoolAttributeValues:    [][]bool{{true, false}},
		eventDoubleAttributeKeys:    [][]string{{"event.response_time"}},
		eventDoubleAttributeValues:  [][]float64{{0.001}},
		eventIntAttributeKeys:       [][]string{{"event.sequence"}},
		eventIntAttributeValues:     [][]int64{{1}},
		eventStrAttributeKeys:       [][]string{{"event.message"}},
		eventStrAttributeValues:     [][]string{{"user login successful"}},
		eventComplexAttributeKeys:   [][]string{{"@bytes@event.payload"}},
		eventComplexAttributeValues: [][]string{{"eyJ1c2VyX2lkIjoxMjM0NX0="}},
		linkTraceIDs:                []string{"00000000000000000000000000000002"},
		linkSpanIDs:                 []string{"0000000000000002"},
		linkTraceStates:             []string{"state2"},
		serviceName:                 "user-service",
		scopeName:                   "auth-scope",
		scopeVersion:                "v1.0.0",
	},
}

var multipleSpans = []*spanRow{
	{
		id:                          "0000000000000001",
		traceID:                     traceID.String(),
		traceState:                  "state1",
		name:                        "GET /api/user",
		kind:                        "server",
		startTime:                   now,
		statusCode:                  "Ok",
		statusMessage:               "success",
		rawDuration:                 1_000_000_000,
		boolAttributeKeys:           []string{"authenticated", "cache_hit"},
		boolAttributeValues:         []bool{true, false},
		doubleAttributeKeys:         []string{"response_time", "cpu_usage"},
		doubleAttributeValues:       []float64{0.123, 45.67},
		intAttributeKeys:            []string{"user_id", "request_size"},
		intAttributeValues:          []int64{12345, 1024},
		strAttributeKeys:            []string{"http.method", "http.url"},
		strAttributeValues:          []string{"GET", "/api/user"},
		complexAttributeKeys:        []string{"@bytes@request_body"},
		complexAttributeValues:      []string{"eyJuYW1lIjoidGVzdCJ9"},
		eventNames:                  []string{"login"},
		eventTimestamps:             []time.Time{now},
		eventBoolAttributeKeys:      [][]string{{"event.authenticated", "event.cached"}},
		eventBoolAttributeValues:    [][]bool{{true, false}},
		eventDoubleAttributeKeys:    [][]string{{"event.response_time"}},
		eventDoubleAttributeValues:  [][]float64{{0.001}},
		eventIntAttributeKeys:       [][]string{{"event.sequence"}},
		eventIntAttributeValues:     [][]int64{{1}},
		eventStrAttributeKeys:       [][]string{{"event.message"}},
		eventStrAttributeValues:     [][]string{{"user login successful"}},
		eventComplexAttributeKeys:   [][]string{{"@bytes@event.payload"}},
		eventComplexAttributeValues: [][]string{{"eyJ1c2VyX2lkIjoxMjM0NX0="}},
		linkTraceIDs:                []string{"00000000000000000000000000000002"},
		linkSpanIDs:                 []string{"0000000000000002"},
		linkTraceStates:             []string{"state2"},
		serviceName:                 "user-service",
		scopeName:                   "auth-scope",
		scopeVersion:                "v1.0.0",
	},
	{
		id:                          "0000000000000003",
		traceID:                     traceID.String(),
		traceState:                  "state1",
		parentSpanID:                "0000000000000001",
		name:                        "SELECT /db/query",
		kind:                        "client",
		startTime:                   now.Add(10 * time.Millisecond),
		statusCode:                  "Ok",
		statusMessage:               "success",
		rawDuration:                 500_000_000,
		boolAttributeKeys:           []string{"db.cached", "db.readonly"},
		boolAttributeValues:         []bool{false, true},
		doubleAttributeKeys:         []string{"db.latency", "db.connections"},
		doubleAttributeValues:       []float64{0.05, 5.0},
		intAttributeKeys:            []string{"db.rows_affected", "db.connection_id"},
		intAttributeValues:          []int64{150, 42},
		strAttributeKeys:            []string{"db.statement", "db.name"},
		strAttributeValues:          []string{"SELECT * FROM users", "userdb"},
		complexAttributeKeys:        []string{"@bytes@db.query_plan"},
		complexAttributeValues:      []string{"UExBTiBTRUxFQ1Q="},
		eventNames:                  []string{"query-start", "query-end"},
		eventTimestamps:             []time.Time{now.Add(10 * time.Millisecond), now.Add(510 * time.Millisecond)},
		eventBoolAttributeKeys:      [][]string{{"db.optimized", "db.indexed"}, {"db.cached", "db.successful"}},
		eventBoolAttributeValues:    [][]bool{{true, false}, {true, false}},
		eventDoubleAttributeKeys:    [][]string{{"db.query_time"}, {"db.result_time"}},
		eventDoubleAttributeValues:  [][]float64{{0.001}, {0.5}},
		eventIntAttributeKeys:       [][]string{{"db.connection_pool_size"}, {"db.result_count"}},
		eventIntAttributeValues:     [][]int64{{10}, {150}},
		eventStrAttributeKeys:       [][]string{{"db.event.type"}, {"db.event.status"}},
		eventStrAttributeValues:     [][]string{{"query_execution_start"}, {"query_execution_complete"}},
		eventComplexAttributeKeys:   [][]string{{"@bytes@db.query_metadata"}, {"@bytes@db.result_metadata"}},
		eventComplexAttributeValues: [][]string{{"eyJxdWVyeV9pZCI6MTIzfQ=="}, {"eyJyb3dfY291bnQiOjE1MH0="}},
		linkTraceIDs:                []string{},
		linkSpanIDs:                 []string{},
		linkTraceStates:             []string{},
		serviceName:                 "db-service",
		scopeName:                   "db-scope",
		scopeVersion:                "v1.0.0",
	},
}
