// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dependency_storage.proto

package storage

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetDependenciesRequest struct {
	// start_time is the start of the time interval to search for the dependencies.
	StartTime *types.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// end_time is the end of the time interval to search for the dependencies.
	EndTime              *types.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetDependenciesRequest) Reset()         { *m = GetDependenciesRequest{} }
func (m *GetDependenciesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDependenciesRequest) ProtoMessage()    {}
func (*GetDependenciesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17393f3b58692e2b, []int{0}
}
func (m *GetDependenciesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDependenciesRequest.Unmarshal(m, b)
}
func (m *GetDependenciesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDependenciesRequest.Marshal(b, m, deterministic)
}
func (m *GetDependenciesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDependenciesRequest.Merge(m, src)
}
func (m *GetDependenciesRequest) XXX_Size() int {
	return xxx_messageInfo_GetDependenciesRequest.Size(m)
}
func (m *GetDependenciesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDependenciesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDependenciesRequest proto.InternalMessageInfo

func (m *GetDependenciesRequest) GetStartTime() *types.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *GetDependenciesRequest) GetEndTime() *types.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

// Dependency represents a relationship between two services.
type Dependency struct {
	// parent is the name of the caller service.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// child is the name of the service being called.
	Child string `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	// call_count is the number of times the parent service called the child service.
	CallCount uint64 `protobuf:"varint,3,opt,name=call_count,json=callCount,proto3" json:"call_count,omitempty"`
	// source contains the origin from where the dependency was extracted.
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_17393f3b58692e2b, []int{1}
}
func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (m *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(m, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Dependency) GetChild() string {
	if m != nil {
		return m.Child
	}
	return ""
}

func (m *Dependency) GetCallCount() uint64 {
	if m != nil {
		return m.CallCount
	}
	return 0
}

func (m *Dependency) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type GetDependenciesResponse struct {
	Dependencies         []*Dependency `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetDependenciesResponse) Reset()         { *m = GetDependenciesResponse{} }
func (m *GetDependenciesResponse) String() string { return proto.CompactTextString(m) }
func (*GetDependenciesResponse) ProtoMessage()    {}
func (*GetDependenciesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_17393f3b58692e2b, []int{2}
}
func (m *GetDependenciesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDependenciesResponse.Unmarshal(m, b)
}
func (m *GetDependenciesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDependenciesResponse.Marshal(b, m, deterministic)
}
func (m *GetDependenciesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDependenciesResponse.Merge(m, src)
}
func (m *GetDependenciesResponse) XXX_Size() int {
	return xxx_messageInfo_GetDependenciesResponse.Size(m)
}
func (m *GetDependenciesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDependenciesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDependenciesResponse proto.InternalMessageInfo

func (m *GetDependenciesResponse) GetDependencies() []*Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func init() {
	proto.RegisterType((*GetDependenciesRequest)(nil), "jaeger.storage.v2.GetDependenciesRequest")
	proto.RegisterType((*Dependency)(nil), "jaeger.storage.v2.Dependency")
	proto.RegisterType((*GetDependenciesResponse)(nil), "jaeger.storage.v2.GetDependenciesResponse")
}

func init() { proto.RegisterFile("dependency_storage.proto", fileDescriptor_17393f3b58692e2b) }

var fileDescriptor_17393f3b58692e2b = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0xa5, 0x6e, 0x6e, 0xf6, 0x4e, 0x50, 0xc3, 0x98, 0xa5, 0x30, 0x1c, 0x7b, 0x9a, 0x3e, 0x64,
	0x50, 0xf1, 0xc1, 0x47, 0x3f, 0xc0, 0xf7, 0xe2, 0x93, 0x08, 0x23, 0x6b, 0xae, 0xdd, 0xa4, 0x4b,
	0xba, 0x24, 0x15, 0x06, 0xfe, 0x02, 0x7f, 0xb5, 0x24, 0x59, 0x75, 0xba, 0x81, 0xbe, 0xe5, 0x9c,
	0x7b, 0xce, 0xb9, 0x1f, 0x81, 0x88, 0x63, 0x89, 0x82, 0xa3, 0xc8, 0x56, 0x13, 0x6d, 0xa4, 0x62,
	0x39, 0xd2, 0x52, 0x49, 0x23, 0xc9, 0xc9, 0x2b, 0xc3, 0x1c, 0x15, 0xad, 0xd9, 0xb7, 0x24, 0xee,
	0xe6, 0x32, 0x97, 0xae, 0x3a, 0xb6, 0x2f, 0x2f, 0x8c, 0xcf, 0x72, 0x29, 0xf3, 0x02, 0xc7, 0x0e,
	0x4d, 0xab, 0x97, 0xb1, 0x99, 0x2f, 0x50, 0x1b, 0xb6, 0x28, 0xbd, 0x60, 0xf8, 0x11, 0x40, 0xef,
	0x01, 0xcd, 0x7d, 0xdd, 0x69, 0x8e, 0x3a, 0xc5, 0x65, 0x85, 0xda, 0x90, 0x6b, 0x00, 0x6d, 0x98,
	0x32, 0x13, 0xeb, 0x89, 0x82, 0x41, 0x30, 0xea, 0x24, 0x31, 0xf5, 0x81, 0xb4, 0x0e, 0xa4, 0x8f,
	0x75, 0x60, 0x1a, 0x3a, 0xb5, 0xc5, 0xe4, 0x0a, 0x0e, 0x50, 0x70, 0x6f, 0xdc, 0xfb, 0xd3, 0xd8,
	0x46, 0xc1, 0x2d, 0x1a, 0x2e, 0x01, 0xbe, 0x06, 0x59, 0x91, 0x1e, 0xb4, 0x4a, 0xa6, 0x50, 0x18,
	0xd7, 0x3b, 0x4c, 0xd7, 0x88, 0x74, 0x61, 0x3f, 0x9b, 0xcd, 0x0b, 0xee, 0x92, 0xc3, 0xd4, 0x03,
	0xd2, 0x07, 0xc8, 0x58, 0x51, 0x4c, 0x32, 0x59, 0x09, 0x13, 0x35, 0x06, 0xc1, 0xa8, 0x99, 0x86,
	0x96, 0xb9, 0xb3, 0x84, 0x0d, 0xd3, 0xb2, 0x52, 0x19, 0x46, 0x4d, 0x1f, 0xe6, 0xd1, 0xf0, 0x19,
	0x4e, 0xb7, 0xd6, 0xd7, 0xa5, 0x14, 0x1a, 0xc9, 0x0d, 0x1c, 0xf2, 0x0d, 0x3e, 0x0a, 0x06, 0x8d,
	0x51, 0x27, 0xe9, 0xd3, 0xad, 0xdb, 0xd3, 0xef, 0xa1, 0xd3, 0x1f, 0x96, 0xe4, 0x1d, 0x8e, 0x37,
	0x6a, 0xc8, 0x38, 0x2a, 0x32, 0x83, 0xa3, 0x5f, 0x1d, 0xc9, 0xf9, 0x8e, 0xcc, 0xdd, 0x9f, 0x12,
	0x5f, 0xfc, 0x47, 0xea, 0x17, 0xb8, 0x0d, 0x9f, 0xda, 0x6b, 0xd5, 0xb4, 0xe5, 0xce, 0x7e, 0xf9,
	0x19, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xa8, 0x90, 0x46, 0x53, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DependencyReaderClient is the client API for DependencyReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DependencyReaderClient interface {
	// GetDependencies loads service dependencies from storage.
	GetDependencies(ctx context.Context, in *GetDependenciesRequest, opts ...grpc.CallOption) (*GetDependenciesResponse, error)
}

type dependencyReaderClient struct {
	cc *grpc.ClientConn
}

func NewDependencyReaderClient(cc *grpc.ClientConn) DependencyReaderClient {
	return &dependencyReaderClient{cc}
}

func (c *dependencyReaderClient) GetDependencies(ctx context.Context, in *GetDependenciesRequest, opts ...grpc.CallOption) (*GetDependenciesResponse, error) {
	out := new(GetDependenciesResponse)
	err := c.cc.Invoke(ctx, "/jaeger.storage.v2.DependencyReader/GetDependencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependencyReaderServer is the server API for DependencyReader service.
type DependencyReaderServer interface {
	// GetDependencies loads service dependencies from storage.
	GetDependencies(context.Context, *GetDependenciesRequest) (*GetDependenciesResponse, error)
}

// UnimplementedDependencyReaderServer can be embedded to have forward compatible implementations.
type UnimplementedDependencyReaderServer struct {
}

func (*UnimplementedDependencyReaderServer) GetDependencies(ctx context.Context, req *GetDependenciesRequest) (*GetDependenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDependencies not implemented")
}

func RegisterDependencyReaderServer(s *grpc.Server, srv DependencyReaderServer) {
	s.RegisterService(&_DependencyReader_serviceDesc, srv)
}

func _DependencyReader_GetDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDependenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyReaderServer).GetDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jaeger.storage.v2.DependencyReader/GetDependencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyReaderServer).GetDependencies(ctx, req.(*GetDependenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DependencyReader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jaeger.storage.v2.DependencyReader",
	HandlerType: (*DependencyReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDependencies",
			Handler:    _DependencyReader_GetDependencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dependency_storage.proto",
}
