// Copyright (c) 2024 The Jaeger Authors.
// SPDX-License-Identifier: Apache-2.0

package adjuster

import (
	"go.opentelemetry.io/collector/pdata/ptrace"

	"github.com/jaegertracing/jaeger/internal/jptrace"
)

var _ Adjuster = (*SpanHashDeduper)(nil)

// DeduplicateSpans creates an adjuster that deduplicates spans by removing all but one span
// with the same hash code. This is particularly useful for scenarios where spans
// may be duplicated during archival, such as with ElasticSearch archival.
//
// The hash code is generated by serializing the span into protobuf bytes and applying
// the FNV hashing algorithm to the serialized data.
//
// To ensure consistent hash codes, this adjuster should be executed after
// SortAttributesAndEvents, which normalizes the order of collections within the span.
func DeduplicateSpans() *SpanHashDeduper {
	return &SpanHashDeduper{}
}

type SpanHashDeduper struct{}

func (SpanHashDeduper) Adjust(traces ptrace.Traces) {
	spansByHash := make(map[int64]ptrace.Span)
	resourceSpans := traces.ResourceSpans()
	spanHasher := jptrace.NewSpanHasher()
	for i := 0; i < resourceSpans.Len(); i++ {
		rs := resourceSpans.At(i)
		scopeSpans := rs.ScopeSpans()
		hashTrace := ptrace.NewTraces()
		hashResourceSpan := hashTrace.ResourceSpans().AppendEmpty()
		hashScopeSpan := hashResourceSpan.ScopeSpans().AppendEmpty()
		hashSpan := hashScopeSpan.Spans().AppendEmpty()
		rs.Resource().Attributes().CopyTo(hashResourceSpan.Resource().Attributes())
		for j := 0; j < scopeSpans.Len(); j++ {
			ss := scopeSpans.At(j)
			spans := ss.Spans()
			ss.Scope().Attributes().CopyTo(hashScopeSpan.Scope().Attributes())
			dedupedSpans := ptrace.NewSpanSlice()
			for k := 0; k < spans.Len(); k++ {
				span := spans.At(k)
				span.CopyTo(hashSpan)
				spanHash, err := spanHasher.SpanHash(hashTrace)
				if err != nil {
					jptrace.AddWarnings(span, err.Error())
				}
				if spanHash == 0 {
					span.CopyTo(dedupedSpans.AppendEmpty())
					continue
				}

				if _, ok := spansByHash[spanHash]; !ok {
					spansByHash[spanHash] = span
					span.CopyTo(dedupedSpans.AppendEmpty())
				}
			}
			dedupedSpans.CopyTo(spans)
		}
	}
}
