// Code generated by mockery v1.0.0. DO NOT EDIT.

// Copyright (c) 2020 The Jaeger Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


package mocks

import (
	pongo2 "github.com/flosch/pongo2/v4"
	mock "github.com/stretchr/testify/mock"
)

// TemplateApplier is an autogenerated mock type for the TemplateApplier type
type TemplateApplier struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx
func (_m *TemplateApplier) Execute(ctx pongo2.Context) (string, error) {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(pongo2.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(pongo2.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
