"groups":
- "name": "jaeger_alerts"
  "rules":
  - "alert": "JaegerCollectorDroppingSpans"
    "annotations":
      "message": |
        {{ $labels.job }} {{ $labels.instance }} is refusing {{ printf "%.2f" $value }}% of received spans.
    "expr": "100 * sum(rate(otelcol_receiver_refused_spans_total[1m])) by (instance, job, namespace) / (sum(rate(otelcol_receiver_accepted_spans_total[1m])) by (instance, job, namespace) + sum(rate(otelcol_receiver_refused_spans_total[1m])) by (instance, job, namespace)) > 1"
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "JaegerExporterFailingSpans"
    "annotations":
      "message": |
        {{ $labels.job }} {{ $labels.instance }} is failing to export {{ printf "%.2f" $value }}% of spans.
    "expr": "100 * sum(rate(otelcol_exporter_send_failed_spans_total[1m])) by (instance, job, namespace) / (sum(rate(otelcol_exporter_sent_spans_total[1m])) by (instance, job, namespace) + sum(rate(otelcol_exporter_send_failed_spans_total[1m])) by (instance, job, namespace)) > 1"
    "for": "15m"
    "labels":
      "severity": "warning"
  - "alert": "JaegerQueryReqsFailing"
    "annotations":
      "message": |
        {{ $labels.job }} {{ $labels.instance }} is seeing {{ printf "%.2f" $value }}% query errors on {{ $labels.operation }}.
    "expr": "100 * sum(rate(jaeger_query_requests_total{result=\"err\"}[1m])) by (instance, job, namespace, operation) / sum(rate(jaeger_query_requests_total[1m])) by (instance, job, namespace, operation)> 1"
    "for": "15m"
    "labels":
      "severity": "warning"
