// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model_test.proto

package prototest

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SpanRefType int32

const (
	SpanRefType_CHILD_OF     SpanRefType = 0
	SpanRefType_FOLLOWS_FROM SpanRefType = 1
)

var SpanRefType_name = map[int32]string{
	0: "CHILD_OF",
	1: "FOLLOWS_FROM",
}
var SpanRefType_value = map[string]int32{
	"CHILD_OF":     0,
	"FOLLOWS_FROM": 1,
}

func (x SpanRefType) String() string {
	return proto.EnumName(SpanRefType_name, int32(x))
}
func (SpanRefType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_model_test_fef2c52f5f26d735, []int{0}
}

type SpanRef struct {
	TraceId              []byte      `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId               []byte      `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	RefType              SpanRefType `protobuf:"varint,3,opt,name=ref_type,json=refType,proto3,enum=prototest.SpanRefType" json:"ref_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SpanRef) Reset()         { *m = SpanRef{} }
func (m *SpanRef) String() string { return proto.CompactTextString(m) }
func (*SpanRef) ProtoMessage()    {}
func (*SpanRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_test_fef2c52f5f26d735, []int{0}
}
func (m *SpanRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpanRef.Unmarshal(m, b)
}
func (m *SpanRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpanRef.Marshal(b, m, deterministic)
}
func (dst *SpanRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpanRef.Merge(dst, src)
}
func (m *SpanRef) XXX_Size() int {
	return xxx_messageInfo_SpanRef.Size(m)
}
func (m *SpanRef) XXX_DiscardUnknown() {
	xxx_messageInfo_SpanRef.DiscardUnknown(m)
}

var xxx_messageInfo_SpanRef proto.InternalMessageInfo

func (m *SpanRef) GetTraceId() []byte {
	if m != nil {
		return m.TraceId
	}
	return nil
}

func (m *SpanRef) GetSpanId() []byte {
	if m != nil {
		return m.SpanId
	}
	return nil
}

func (m *SpanRef) GetRefType() SpanRefType {
	if m != nil {
		return m.RefType
	}
	return SpanRefType_CHILD_OF
}

type DependencyLink struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Child                string   `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	CallCount            uint64   `protobuf:"varint,3,opt,name=call_count,json=callCount,proto3" json:"call_count,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DependencyLink) Reset()         { *m = DependencyLink{} }
func (m *DependencyLink) String() string { return proto.CompactTextString(m) }
func (*DependencyLink) ProtoMessage()    {}
func (*DependencyLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_model_test_fef2c52f5f26d735, []int{1}
}
func (m *DependencyLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DependencyLink.Unmarshal(m, b)
}
func (m *DependencyLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DependencyLink.Marshal(b, m, deterministic)
}
func (dst *DependencyLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DependencyLink.Merge(dst, src)
}
func (m *DependencyLink) XXX_Size() int {
	return xxx_messageInfo_DependencyLink.Size(m)
}
func (m *DependencyLink) XXX_DiscardUnknown() {
	xxx_messageInfo_DependencyLink.DiscardUnknown(m)
}

var xxx_messageInfo_DependencyLink proto.InternalMessageInfo

func (m *DependencyLink) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *DependencyLink) GetChild() string {
	if m != nil {
		return m.Child
	}
	return ""
}

func (m *DependencyLink) GetCallCount() uint64 {
	if m != nil {
		return m.CallCount
	}
	return 0
}

func (m *DependencyLink) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterType((*SpanRef)(nil), "prototest.SpanRef")
	proto.RegisterType((*DependencyLink)(nil), "prototest.DependencyLink")
	proto.RegisterEnum("prototest.SpanRefType", SpanRefType_name, SpanRefType_value)
}

func init() { proto.RegisterFile("model_test.proto", fileDescriptor_model_test_fef2c52f5f26d735) }

var fileDescriptor_model_test_fef2c52f5f26d735 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x5d, 0x4b, 0xc3, 0x30,
	0x18, 0x85, 0xad, 0xce, 0x7e, 0xbc, 0x96, 0x51, 0x82, 0xcc, 0x7a, 0x21, 0x8c, 0x5d, 0x0d, 0xc1,
	0x82, 0xfa, 0x13, 0x36, 0x8a, 0x85, 0x4a, 0x21, 0x13, 0xbc, 0x0c, 0x35, 0x7d, 0x87, 0xc5, 0x9a,
	0x84, 0x34, 0xbd, 0xe8, 0xbf, 0x97, 0x24, 0x43, 0x76, 0x95, 0x3c, 0xe7, 0xc0, 0x73, 0x12, 0xc8,
	0x7e, 0x65, 0x87, 0x03, 0x33, 0x38, 0x9a, 0x42, 0x69, 0x69, 0x24, 0x49, 0xdc, 0x61, 0x83, 0x8d,
	0x82, 0xe8, 0xa0, 0x5a, 0x41, 0xf1, 0x48, 0xee, 0x21, 0x36, 0xba, 0xe5, 0xc8, 0xfa, 0x2e, 0x0f,
	0xd6, 0xc1, 0x36, 0xa5, 0x91, 0xe3, 0xaa, 0x23, 0x77, 0x10, 0x8d, 0xaa, 0x15, 0xb6, 0xb9, 0x74,
	0x4d, 0x68, 0xb1, 0xea, 0xc8, 0x33, 0xc4, 0x1a, 0x8f, 0xcc, 0xcc, 0x0a, 0xf3, 0xab, 0x75, 0xb0,
	0x5d, 0xbe, 0xac, 0x8a, 0x7f, 0x79, 0x71, 0x32, 0x7f, 0xcc, 0x0a, 0x69, 0xa4, 0xfd, 0x65, 0x33,
	0xc1, 0x72, 0x8f, 0x0a, 0x45, 0x87, 0x82, 0xcf, 0x75, 0x2f, 0x7e, 0xc8, 0x0a, 0x42, 0xd5, 0x6a,
	0x14, 0xc6, 0xcd, 0x26, 0xf4, 0x44, 0xe4, 0x16, 0xae, 0xf9, 0x77, 0x3f, 0xf8, 0xcd, 0x84, 0x7a,
	0x20, 0x0f, 0x00, 0xbc, 0x1d, 0x06, 0xc6, 0xe5, 0x24, 0x8c, 0x1b, 0x5d, 0xd0, 0xc4, 0x26, 0x3b,
	0x1b, 0x58, 0xd9, 0x28, 0x27, 0xcd, 0x31, 0x5f, 0x78, 0x99, 0xa7, 0xc7, 0x27, 0xb8, 0x39, 0x7b,
	0x0e, 0x49, 0x21, 0xde, 0xbd, 0x55, 0xf5, 0x9e, 0x35, 0x65, 0x76, 0x41, 0x32, 0x48, 0xcb, 0xa6,
	0xae, 0x9b, 0xcf, 0x03, 0x2b, 0x69, 0xf3, 0x9e, 0x05, 0x5f, 0xa1, 0xfb, 0xc5, 0xeb, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb5, 0x7b, 0x1f, 0x45, 0x3d, 0x01, 0x00, 0x00,
}
