// Copyright (c) The Jaeger Authors.
// SPDX-License-Identifier: Apache-2.0
//
// Run 'make generate-mocks' to regenerate.

// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	storage_v1 "github.com/jaegertracing/jaeger/internal/proto-gen/storage_v1"
)

// SpanReaderPlugin_GetTraceServer is an autogenerated mock type for the SpanReaderPlugin_GetTraceServer type
type SpanReaderPlugin_GetTraceServer struct {
	mock.Mock
}

type SpanReaderPlugin_GetTraceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *SpanReaderPlugin_GetTraceServer) EXPECT() *SpanReaderPlugin_GetTraceServer_Expecter {
	return &SpanReaderPlugin_GetTraceServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with no fields
func (_m *SpanReaderPlugin_GetTraceServer) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// SpanReaderPlugin_GetTraceServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type SpanReaderPlugin_GetTraceServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *SpanReaderPlugin_GetTraceServer_Expecter) Context() *SpanReaderPlugin_GetTraceServer_Context_Call {
	return &SpanReaderPlugin_GetTraceServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *SpanReaderPlugin_GetTraceServer_Context_Call) Run(run func()) *SpanReaderPlugin_GetTraceServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_Context_Call) Return(_a0 context.Context) *SpanReaderPlugin_GetTraceServer_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_Context_Call) RunAndReturn(run func() context.Context) *SpanReaderPlugin_GetTraceServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *SpanReaderPlugin_GetTraceServer) RecvMsg(m any) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SpanReaderPlugin_GetTraceServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type SpanReaderPlugin_GetTraceServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *SpanReaderPlugin_GetTraceServer_Expecter) RecvMsg(m interface{}) *SpanReaderPlugin_GetTraceServer_RecvMsg_Call {
	return &SpanReaderPlugin_GetTraceServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *SpanReaderPlugin_GetTraceServer_RecvMsg_Call) Run(run func(m any)) *SpanReaderPlugin_GetTraceServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_RecvMsg_Call) Return(_a0 error) *SpanReaderPlugin_GetTraceServer_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_RecvMsg_Call) RunAndReturn(run func(any) error) *SpanReaderPlugin_GetTraceServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *SpanReaderPlugin_GetTraceServer) Send(_a0 *storage_v1.SpansResponseChunk) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*storage_v1.SpansResponseChunk) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SpanReaderPlugin_GetTraceServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type SpanReaderPlugin_GetTraceServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *storage_v1.SpansResponseChunk
func (_e *SpanReaderPlugin_GetTraceServer_Expecter) Send(_a0 interface{}) *SpanReaderPlugin_GetTraceServer_Send_Call {
	return &SpanReaderPlugin_GetTraceServer_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *SpanReaderPlugin_GetTraceServer_Send_Call) Run(run func(_a0 *storage_v1.SpansResponseChunk)) *SpanReaderPlugin_GetTraceServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*storage_v1.SpansResponseChunk))
	})
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_Send_Call) Return(_a0 error) *SpanReaderPlugin_GetTraceServer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_Send_Call) RunAndReturn(run func(*storage_v1.SpansResponseChunk) error) *SpanReaderPlugin_GetTraceServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *SpanReaderPlugin_GetTraceServer) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SpanReaderPlugin_GetTraceServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type SpanReaderPlugin_GetTraceServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *SpanReaderPlugin_GetTraceServer_Expecter) SendHeader(_a0 interface{}) *SpanReaderPlugin_GetTraceServer_SendHeader_Call {
	return &SpanReaderPlugin_GetTraceServer_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *SpanReaderPlugin_GetTraceServer_SendHeader_Call) Run(run func(_a0 metadata.MD)) *SpanReaderPlugin_GetTraceServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_SendHeader_Call) Return(_a0 error) *SpanReaderPlugin_GetTraceServer_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *SpanReaderPlugin_GetTraceServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *SpanReaderPlugin_GetTraceServer) SendMsg(m any) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(any) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SpanReaderPlugin_GetTraceServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type SpanReaderPlugin_GetTraceServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *SpanReaderPlugin_GetTraceServer_Expecter) SendMsg(m interface{}) *SpanReaderPlugin_GetTraceServer_SendMsg_Call {
	return &SpanReaderPlugin_GetTraceServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *SpanReaderPlugin_GetTraceServer_SendMsg_Call) Run(run func(m any)) *SpanReaderPlugin_GetTraceServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(any))
	})
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_SendMsg_Call) Return(_a0 error) *SpanReaderPlugin_GetTraceServer_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_SendMsg_Call) RunAndReturn(run func(any) error) *SpanReaderPlugin_GetTraceServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *SpanReaderPlugin_GetTraceServer) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SpanReaderPlugin_GetTraceServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type SpanReaderPlugin_GetTraceServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *SpanReaderPlugin_GetTraceServer_Expecter) SetHeader(_a0 interface{}) *SpanReaderPlugin_GetTraceServer_SetHeader_Call {
	return &SpanReaderPlugin_GetTraceServer_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *SpanReaderPlugin_GetTraceServer_SetHeader_Call) Run(run func(_a0 metadata.MD)) *SpanReaderPlugin_GetTraceServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_SetHeader_Call) Return(_a0 error) *SpanReaderPlugin_GetTraceServer_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *SpanReaderPlugin_GetTraceServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *SpanReaderPlugin_GetTraceServer) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// SpanReaderPlugin_GetTraceServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type SpanReaderPlugin_GetTraceServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *SpanReaderPlugin_GetTraceServer_Expecter) SetTrailer(_a0 interface{}) *SpanReaderPlugin_GetTraceServer_SetTrailer_Call {
	return &SpanReaderPlugin_GetTraceServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *SpanReaderPlugin_GetTraceServer_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *SpanReaderPlugin_GetTraceServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_SetTrailer_Call) Return() *SpanReaderPlugin_GetTraceServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *SpanReaderPlugin_GetTraceServer_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *SpanReaderPlugin_GetTraceServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}

// NewSpanReaderPlugin_GetTraceServer creates a new instance of SpanReaderPlugin_GetTraceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpanReaderPlugin_GetTraceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpanReaderPlugin_GetTraceServer {
	mock := &SpanReaderPlugin_GetTraceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
