name: CIT Hotrod

on:
  workflow_call:

# See https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
permissions:
  contents: read

jobs:
  hotrod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        runtime: [docker, k8s]
          
    steps:
    - uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: ./.github/actions/setup-go
      with:
        go-version: 1.26.x

    - uses: ./.github/actions/setup-node.js

    - uses: ./.github/actions/setup-branch

    - uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

    - name: Define BUILD_FLAGS var if running on a Pull Request
      run: |
        case ${GITHUB_EVENT_NAME} in
          pull_request)
            echo "BUILD_FLAGS=-l -p linux/amd64" >> ${GITHUB_ENV}
            ;;
          *)
            echo "BUILD_FLAGS=" >> ${GITHUB_ENV}
            ;;
        esac
    - name: Install kubectl
      if: matrix.runtime == 'k8s'
      uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v4
      with:
        version: 'latest'
  
    - name: Create k8s Kind Cluster
      if: matrix.runtime == 'k8s'
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1

    - name: Build, test, and publish hotrod image
      run:  bash scripts/build/build-hotrod-image.sh ${{ env.BUILD_FLAGS }} -r ${{ matrix.runtime }}
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
