# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

name: "CI Orchestrator: Stage 2 (Unit Tests)"

on:
  workflow_call:

permissions:
  contents: read

jobs:
  unit-tests:
    uses: ./.github/workflows/ci-unit-tests.yml
    secrets: inherit

  ai-sidecar-gemini:
    uses: ./.github/workflows/ci-ai-sidecar-gemini.yml
    secrets: inherit

  ai-sidecar-ollama:
    uses: ./.github/workflows/ci-ai-sidecar-ollama.yml
    secrets: inherit
