name: "CI Stage: Tier 2 (Unit Tests)"

on:
  workflow_call:

# Grant all permissions to allow child workflows to request what they need
# Child workflows can downgrade permissions as needed (principle of least privilege)
permissions: write-all

jobs:
  unit-tests:
    uses: ./.github/workflows/ci-unit-tests.yml
    secrets: inherit
