# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0

name: "Waiting for Author"

on:
  pull_request_target:
    types: [synchronize]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write

jobs:
  triage:
    if: ${{ github.event.issue.pull_request || github.event.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Manage Waiting for Author Label
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          script: |
            const script = require('./.github/scripts/waiting-for-author.js')
            await script({github, context, core})
